// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, getApiKeyByKey, getApiKeysByCustomer, createApiKey, updateApiKey, deleteApiKey, validateApiKey,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  // Storefront — customers + sessions + plans + orders
  getCustomers, getCustomerById, findCustomerByEmail,
  createCustomer, verifyCustomerPassword, setCustomerPassword,
  findCustomerByGoogleSub, upsertGoogleCustomer, setCustomerTotp,
  updateCustomer, markEmailVerified, deleteCustomer,
  hashToken, createCustomerSession, findCustomerSessionByToken,
  revokeCustomerSession, revokeAllSessionsForCustomer, pruneExpiredSessions,
  getPricingPlans, getPricingPlanById, createPricingPlan,
  updatePricingPlan, deletePricingPlan, planToApiKeyPolicy,
  createOrder, getOrderById, getOrders,
  cancelOrder, markOrderRefunded, confirmOrderAtomic,
  attachApibankOrder, findOrderByApibankRef,
  exportDb, importDb,
} from "@/lib/db/index.js";
